---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: quorum
  region: eu-west-3
  version: "1.26"

# It is recommended that you let eksctl deploy a new VPC for your cluster, it will automatically tag the subnets with the appropriate tags. You may use an existing VPC if you wish but take note of the necessary subnet tags: https://github.com/weaveworks/eksctl/blob/main/examples/04-existing-vpc.yaml https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html
vpc:
  id: vpc-04e0c4bb3f3c1d2ff
  cidr: "10.0.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    public:
      public-a:
        id: subnet-005605b375d6b8458
      public-b:
        id: subnet-088774a8543fa4498
      public-c:
        id: subnet-090a5a67de49ff73d
    private:
      private-a:
        id: subnet-0f2fa0dd5db4c3073
      private-b:
        id: subnet-09a7e37418a411caa
      private-c:
        id: subnet-07327a70758a42045

managedNodeGroups:
  - name: ngrp-quorum
    instanceType: m5.xlarge
    desiredCapacity: 8 # increase this capacity if you need member/rpc nodes or more validators
    privateNetworking: true
    labels: { role: workers }
    subnets:
      - private-a
      - private-b
      - private-c
    iam:
      withAddonPolicies:
        ebs: true
        efs: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 60

# optional but recommended
#secretsEncryption:
#  keyARN: "arn:aws:kms:us-east-2:..."

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: quorum-ebs-efs-csi-drivers
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
        efsCSIController: true
      roleName: quorum-ebs-efs-csi-drivers
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
      roleName: quorum-ebs-csi-drivers
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
      roleName: quorum-efs-csi-drivers

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest